version: '3.2'

services:
  mediabox-deluge:
    image: binhex/arch-delugevpn
    container_name: mediabox-deluge
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PHP_TZ=${TIME_ZONE}
      - UMASK=022
      - NAME_SERVERS=${DELUGE_DNS}
      - LAN_NETWORK=192.168.1.0/24
      - ENABLE_PRIVOXY=no
      - STRICT_PORT_FORWARD=${DELUGE_VPN_STRICT_PORT_FORWARD}
      - VPN_PROV=${DELUGE_VPN_PROV}
      - VPN_USER=${DELUGE_VPN_USER}
      - VPN_PASS=${DELUGE_VPN_PASS}
      - VPN_ENABLED=${DELUGE_VPN_ENABLED}
      - DELUGE_DAEMON_LOG_LEVEL=warning
      - DELUGE_WEB_LOG_LEVEL=warning
      - DEBUG=false
      - VIRTUAL_HOST=${DELUGE_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=8112
      - LETSENCRYPT_HOST=${DELUGE_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/deluge:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DATA_PATH}:/mediabox
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      - mediabox-torrent
      - mediabox-proxy
  
  mediabox-sonarr:
    image: linuxserver/sonarr
    container_name: mediabox-sonarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${SONARR_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=8989
      - LETSENCRYPT_HOST=${SONARR_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DATA_PATH}/tv:/tv
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
  
  mediabox-radarr:
    image: linuxserver/radarr
    container_name: mediabox-radarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${RADARR_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=7878
      - LETSENCRYPT_HOST=${RADARR_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DATA_PATH}/movies:/movies
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy

  mediabox-bazarr:
    image: linuxserver/bazarr
    container_name: mediabox-bazarr
    depends_on:
      - mediabox-sonarr
      - mediabox-radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${BAZARR_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=6767
      - LETSENCRYPT_HOST=${BAZARR_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${DATA_PATH}/movies:/movies
      - ${DATA_PATH}/tv:/tv
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy

  mediabox-jackett:
    image: linuxserver/jackett
    container_name: mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${JACKETT_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=9117
      - LETSENCRYPT_HOST=${JACKETT_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/jackett:/config
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy

  mediabox-webdav:
    image: bytemark/webdav
    container_name: mediabox-webdav
    environment:
      - USERNAME=${WEBDAV_USERNAME}
      - PASSWORD=${WEBDAV_PASSWORD}
      - VIRTUAL_HOST=${WEBDAV_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${WEBDAV_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${DATA_PATH}:/var/lib/dav/data/mediabox
      - ${DOWNLOADS_PATH}:/var/lib/dav/data/downloads
      - ${MOUNT_PATH}:/var/lib/dav/data/mnt/rclone:rw,rslave
    restart: unless-stopped
    networks:
      - mediabox-proxy

  mediabox-filestash:
    image: machines/filestash
    container_name: mediabox-filestash
    environment:
      - APPLICATION_URL=filestash.${DOMAIN}
      - VIRTUAL_HOST=${FILESTASH_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=8334
      - LETSENCRYPT_HOST=${FILESTASH_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: unless-stopped
    networks:
      - mediabox-proxy

networks:
  mediabox-torrent:
    driver: bridge
  mediabox-proxy:
    driver: bridge
