version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: mediabox-nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${CONFIG_PATH}/nginx-proxy/conf.d:/etc/nginx/conf.d
      - ${CONFIG_PATH}/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ${CONFIG_PATH}/nginx-proxy/html:/usr/share/nginx/html
      - ${CONFIG_PATH}/nginx-proxy/dhparam:/etc/nginx/dhparam
      - ${CONFIG_PATH}/certs:/etc/nginx/certs:ro
    restart: unless-stopped
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'
    networks:
     - torrent

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: mediabox-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_PATH}/nginx-proxy/conf.d:/etc/nginx/conf.d
      - ${CONFIG_PATH}/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ${CONFIG_PATH}/nginx-proxy/html:/usr/share/nginx/html
      - ${CONFIG_PATH}/nginx-proxy/dhparam:/etc/nginx/dhparam
      - ${CONFIG_PATH}/certs:/etc/nginx/certs:rw
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=mediabox-nginx-proxy
      - DEBUG=false
    restart: unless-stopped

networks:
  torrent:
    driver: bridge
