version: '3.2'

services:
  mediabox-deluge:
    image: binhex/arch-delugevpn
    container_name: mediabox-deluge
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PHP_TZ=${TIME_ZONE}
      - UMASK=022
      - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
      - LAN_NETWORK=192.168.1.0/24
      - ENABLE_PRIVOXY=no
      - STRICT_PORT_FORWARD=${VPN_STRICT_PORT_FORWARD}
      - VPN_PROV=${VPN_PROV}
      - VPN_USER=${VPN_USER}
      - VPN_PASS=${VPN_PASS}
      - VPN_ENABLED=${VPN_ENABLED}
      - DELUGE_DAEMON_LOG_LEVEL=warning
      - DELUGE_WEB_LOG_LEVEL=warning
      - DEBUG=false
      - VIRTUAL_HOST=download.${DOMAIN}
      - VIRTUAL_PORT=8112
      - LETSENCRYPT_HOST=download.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/deluge:/config
      - ${DOWNLOADS_PATH}:/data
      - ${DATA_PATH}:/mediabox
      - type: bind
        source: ${MOUNT_PATH}
        target: /cloud
        bind:
          propagation: rslave
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946
    restart: unless-stopped
    privileged: true
    networks:
      - mediabox-torrent
      - mediabox-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  mediabox-sonarr:
    image: linuxserver/sonarr
    container_name: mediabox-sonarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=sonarr.${DOMAIN}
      - VIRTUAL_PORT=8989
      - LETSENCRYPT_HOST=sonarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DATA_PATH}/tv:/tv
      - type: bind
        source: ${MOUNT_PATH}
        target: /cloud
        bind:
          propagation: rslave
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  mediabox-radarr:
    image: linuxserver/radarr
    container_name: mediabox-radarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=radarr.${DOMAIN}
      - VIRTUAL_PORT=7878
      - LETSENCRYPT_HOST=radarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DATA_PATH}/movies:/movies
      - type: bind
        source: ${MOUNT_PATH}
        target: /cloud
        bind:
          propagation: rslave
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  mediabox-lidarr:
    image: linuxserver/lidarr
    container_name: mediabox-lidarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=lidarr.${DOMAIN}
      - VIRTUAL_PORT=8686
      - LETSENCRYPT_HOST=lidarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/lidarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DATA_PATH}/music:/music
      - type: bind
        source: ${MOUNT_PATH}
        target: /cloud
        bind:
          propagation: rslave
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mediabox-bazarr:
    image: linuxserver/bazarr
    container_name: mediabox-bazarr
    depends_on:
      - mediabox-sonarr
      - mediabox-radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=bazarr.${DOMAIN}
      - VIRTUAL_PORT=6767
      - LETSENCRYPT_HOST=bazarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${DATA_PATH}/movies:/movies
      - ${DATA_PATH}/tv:/tv
      - type: bind
        source: ${MOUNT_PATH}
        target: /cloud
        bind:
          propagation: rslave
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mediabox-jackett:
    image: linuxserver/jackett
    container_name: mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=jackett.${DOMAIN}
      - VIRTUAL_PORT=9117
      - LETSENCRYPT_HOST=jackett.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  mediabox-jellyfin:
    image: linuxserver/jellyfin
    container_name: mediabox-jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=stream.${DOMAIN}
      - VIRTUAL_PORT=8096
      - LETSENCRYPT_HOST=stream.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${DATA_PATH}:/data
      - type: bind
        source: ${MOUNT_PATH}
        target: /cloud
        bind:
          propagation: rslave
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - mediabox-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  mediabox-nextcloud-db:
    image: mariadb
    container_name: mediabox-nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
    volumes:
      - ${CONFIG_PATH}/nextcloud-db:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    networks:
      - mediabox-cloud
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  mediabox-nextcloud:
    image: linuxserver/nextcloud
    container_name: mediabox-nextcloud
    depends_on:
      - mediabox-nextcloud-db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=cloud.${DOMAIN}
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=cloud.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/nextcloud:/config
      - ${NEXTCLOUD_PATH}:/data
      - type: bind
        source: ${MOUNT_PATH}
        target: /cloud
        bind:
          propagation: rslave
      - ${DATA_PATH}:/mediabox
    ports:
      - 5443:443
    restart: unless-stopped
    networks:
      - mediabox-proxy
      - mediabox-cloud
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  mediabox-torrent:
    driver: bridge
  mediabox-proxy:
    driver: bridge
  mediabox-cloud:
    driver: bridge
