version: '3'

services:
  mediabox-rtorrent:
      image: binhex/arch-rtorrentvpn
      container_name: mediabox-rtorrent
      depends_on:
        - mediabox-nginx-proxy
        
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - PHP_TZ=${TIME_ZONE}
        - DEBUG=false
        - UMASK=022
        - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
        - LAN_NETWORK=192.168.1.0/24
        - ENABLE_RPC2_AUTH=yes
        - ENABLE_RPC2=yes
        - ENABLE_AUTODL_IRSSI=no
        - ENABLE_PRIVOXY=no
        - STRICT_PORT_FORWARD=${VPN_STRICT_PORT_FORWARD}
        - VPN_PROV=${VPN_PROV}
        - VPN_USER=${VPN_USER}
        - VPN_PASS=${VPN_PASS}
        - VPN_ENABLED=${VPN_ENABLED}
        - VIRTUAL_HOST=download.${DOMAIN}
        - VIRTUAL_PORT=9080
        - LETSENCRYPT_HOST=download.${DOMAIN}
        - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      volumes:
        - ${CONFIG_PATH}/rtorrent:/config
        - ${DATA_PATH}/downloads:/data 
        - /etc/localtime:/etc/localtime:ro
      ports:
        - 9080:9080
        - 9443:9443
        - 8118:8118
      restart: unless-stopped
      privileged: true
      networks:
        - mediabox-torrent
  
  mediabox-sonarr:
    image: linuxserver/sonarr
    container_name: mediabox-sonarr
    depends_on:
      - mediabox-nginx-proxy
      
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=sonarr.${DOMAIN}
      - LETSENCRYPT_HOST=sonarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=8989
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - mediabox-torrent
  
  mediabox-radarr:
    image: linuxserver/radarr
    container_name: mediabox-radarr
    depends_on:
      - mediabox-nginx-proxy
      
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=radarr.${DOMAIN}
      - LETSENCRYPT_HOST=radarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=7878
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - mediabox-torrent
  
  mediabox-lidarr:
    image: linuxserver/lidarr
    container_name: mediabox-lidarr
    depends_on:
      - mediabox-nginx-proxy
      
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=lidarr.${DOMAIN}
      - LETSENCRYPT_HOST=lidarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=8686
    volumes:
      - ${CONFIG_PATH}/lidarr:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/music:/music
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - mediabox-torrent

  mediabox-bazarr:
    image: linuxserver/bazarr
    container_name: mediabox-bazarr
    depends_on:
      - mediabox-nginx-proxy
      
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=bazarr.${DOMAIN}
      - LETSENCRYPT_HOST=bazarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=6767
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${DATA_PATH}/movies:/movies
      - ${DATA_PATH}/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - mediabox-torrent

  mediabox-jackett:
    image: linuxserver/jackett
    container_name: mediabox-jackett
    depends_on:
      - mediabox-nginx-proxy
      
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=jackett.${DOMAIN}
      - LETSENCRYPT_HOST=jackett.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=9117
    volumes:
      - ${CONFIG_PATH}/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - mediabox-torrent
  
  mediabox-jellyfin:
    image: linuxserver/jellyfin
    container_name: mediabox-jellyfin
    depends_on:
      - mediabox-nginx-proxy
      
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=jellyfin.${DOMAIN}
      - LETSENCRYPT_HOST=jellyfin.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=8096
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${DATA_PATH}/tv:/data/tvshows
      - ${DATA_PATH}/movies:/data/movies
      - ${DATA_PATH}/music:/data/music
    ports:
      - 8096:8096
    restart: unless-stopped

  mediabox-nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: mediabox-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  mediabox-torrent:
    driver: bridge
