version: '3'

services:
  seedbox-rtorrent:
    image: linuxserver/rutorrent
    container_name: seedbox-rtorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_COMPOSE_PATH}/seedbox-rtorrent:/config
      - ${CLOUD_PATH}/downloads:/downloads
    ports:
      - 8033:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - seedbox

  seedbox-sonarr:
    image: linuxserver/sonarr
    container_name: seedbox-sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - ${DOCKER_COMPOSE_PATH}/seedbox-sonarr:/config
      - ${CLOUD_PATH}/tv:/tv
      - ${CLOUD_PATH}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - seedbox
  
  seedbox-radarr:
    image: linuxserver/radarr
    container_name: seedbox-radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${CLOUD_PATH}
    volumes:
      - ${DOCKER_COMPOSE_PATH}/seedbox-radarr:/config
      - ${CLOUD_PATH}/movies:/movies
      - ${CLOUD_PATH}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - seedbox

  seedbox-lidarr:
    image: linuxserver/lidarr
    container_name: seedbox-lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${CLOUD_PATH}
    volumes:
      - ${DOCKER_COMPOSE_PATH}/seedbox-lidarr:/config
      - ${CLOUD_PATH}/music:/music
      - ${CLOUD_PATH}/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - seedbox

  seedbox-bazarr:
    image: linuxserver/bazarr
    container_name: seedbox-bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${CLOUD_PATH}
    volumes:
      - ${DOCKER_COMPOSE_PATH}/seedbox-bazarr:/config
      - ${CLOUD_PATH}/movies:/movies
      - ${CLOUD_PATH}/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - seedbox

  seedbox-jackett:
    image: linuxserver/jackett
    container_name: seedbox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${CLOUD_PATH}
    volumes:
      - ${DOCKER_COMPOSE_PATH}/seedbox-jackett:/config
      - ${CLOUD_PATH}/torrentsblackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - seedbox
    
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${CLOUD_PATH}
    volumes:
      - ${DOCKER_COMPOSE_PATH}/jellyfin:/config
      - ${CLOUD_PATH}/tv:/data/tvshows
      - ${CLOUD_PATH}/movies:/data/movies
      - ${CLOUD_PATH}/music:/data/music
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - cloud

  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${CLOUD_PATH}
    volumes:
      - ${DOCKER_COMPOSE_PATH}/duplicati:/config
      - /home/puser/duplicati-backups:/backups
      - /home/puser:/source
    ports:
      - 8200:8200
    restart: unless-stopped
    networks:
      - cloud

  organizr:
    image: organizrtools/organizr-v2
    container_name: organizr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_COMPOSE_PATH}/organizr:/config
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - cloud
      - seedbox

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - ${DOCKER_COMPOSE_PATH}/filebrowser/database.db:/database.db
      - ${CLOUD_PATH}:/srv
    ports:
      - 8080:80
    restart: unless-stopped
    networks:
      - cloud

networks:
  seedbox:
    driver: bridge
  cloud:
    driver: bridge
