version: '3'

services:
  mediabox-deluge:
      image: binhex/arch-delugevpn
      container_name: mediabox-deluge
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - PHP_TZ=${TIME_ZONE}
        - UMASK=022
        - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
        - LAN_NETWORK=192.168.1.0/24
        - ENABLE_PRIVOXY=no
        - STRICT_PORT_FORWARD=${VPN_STRICT_PORT_FORWARD}
        - VPN_PROV=${VPN_PROV}
        - VPN_USER=${VPN_USER}
        - VPN_PASS=${VPN_PASS}
        - VPN_ENABLED=${VPN_ENABLED}
        - DELUGE_DAEMON_LOG_LEVEL=warning
        - DELUGE_WEB_LOG_LEVEL=warning
        - DEBUG=false
        - VIRTUAL_HOST=download.${DOMAIN}
        - VIRTUAL_PORT=8112
        - LETSENCRYPT_HOST=download.${DOMAIN}
        - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      volumes:
        - ${CONFIG_PATH}/deluge:/config
        - ${DATA_PATH}/downloads:/data 
        - /etc/localtime:/etc/localtime:ro
      ports:
        - 8112:8112
        - 58846:58846
        - 58946:58946
      restart: unless-stopped
      privileged: true
      networks:
        - mediabox-torrent
        - mediabox-proxy
  
  mediabox-sonarr:
    image: linuxserver/sonarr
    container_name: mediabox-sonarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=sonarr.${DOMAIN}
      - VIRTUAL_PORT=8989
      - LETSENCRYPT_HOST=sonarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/tv:/tv
      - ${CLOUD_MOUNT_PATH}:/cloud
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
  
  mediabox-radarr:
    image: linuxserver/radarr
    container_name: mediabox-radarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=radarr.${DOMAIN}
      - VIRTUAL_PORT=7878
      - LETSENCRYPT_HOST=radarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/movies:/movies
      - ${CLOUD_MOUNT_PATH}:/cloud
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
  
  mediabox-lidarr:
    image: linuxserver/lidarr
    container_name: mediabox-lidarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=lidarr.${DOMAIN}
      - VIRTUAL_PORT=8686
      - LETSENCRYPT_HOST=lidarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/lidarr:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/music:/music
      - ${CLOUD_MOUNT_PATH}:/cloud
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy

  mediabox-bazarr:
    image: linuxserver/bazarr
    container_name: mediabox-bazarr
    depends_on:
      - mediabox-sonarr
      - mediabox-radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=bazarr.${DOMAIN}
      - VIRTUAL_PORT=6767
      - LETSENCRYPT_HOST=bazarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${DATA_PATH}/movies:/movies
      - ${DATA_PATH}/tv:/tv
      - ${CLOUD_MOUNT_PATH}:/cloud
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy

  mediabox-jackett:
    image: linuxserver/jackett
    container_name: mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=jackett.${DOMAIN}
      - VIRTUAL_PORT=9117
      - LETSENCRYPT_HOST=jackett.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
  
  mediabox-jellyfin:
    image: linuxserver/jellyfin
    container_name: mediabox-jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=jellyfin.${DOMAIN},stream.${DOMAIN}
      - VIRTUAL_PORT=8096
      - LETSENCRYPT_HOST=jellyfin.${DOMAIN},stream.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${DATA_PATH}/tv:/data/tvshows
      - ${DATA_PATH}/movies:/data/movies
      - ${DATA_PATH}/music:/data/music
      - ${CLOUD_MOUNT_PATH}:/data/remote
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - mediabox-proxy

  mediabox-filebrowser:
    image: filebrowser/filebrowser
    container_name: mediabox-filebrowser
    environment:
      - VIRTUAL_HOST=cloud.${DOMAIN},filebrowser.${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=cloud.${DOMAIN},filebrowser.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/filebrowser/database.db:/database.db
      - ${FILEBROWSER_SRC}:/srv
    ports:
      - 8282:80
    restart: unless-stopped
    networks:
      - mediabox-proxy

  mediabox-rclone:
    image: pfidr/rclone
    container_name: mediabox-rclone
    environment:
      - TZ=${TIME_ZONE}
      - CHECK_URL=${RCLONE_CHECK_URL}
      - RCLONE_CMD=${RCLONE_CMD}
      - SYNC_OPTS=-v --exclude /downloads/** --transfers 32 --min-age 15m --exclude-if-present .rcloneignore
      - SYNC_DEST=${RCLONE_SYNC_DEST}
      - SYNC_SRC=/data
      - CRON=${RCLONE_CRON}
      - OUTPUT_LOG=true
      - ROTATE_LOG=2
    volumes:
      - ${RCLONE_CONF_PATH}:/config
      - ${CONFIG_PATH}/rclone/logs:/logs
      - ${DATA_PATH}:/data
    restart: unless-stopped


networks:
  mediabox-torrent:
    driver: bridge
  mediabox-proxy:
    driver: bridge
