version: '3.2'

services:
  mediabox-deluge:
    image: binhex/arch-delugevpn
    container_name: mediabox-deluge
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PHP_TZ=${TIME_ZONE}
      - UMASK=022
      - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
      - LAN_NETWORK=192.168.1.0/24
      - ENABLE_PRIVOXY=no
      - STRICT_PORT_FORWARD=${VPN_STRICT_PORT_FORWARD}
      - VPN_PROV=${VPN_PROV}
      - VPN_USER=${VPN_USER}
      - VPN_PASS=${VPN_PASS}
      - VPN_ENABLED=${VPN_ENABLED}
      - DELUGE_DAEMON_LOG_LEVEL=warning
      - DELUGE_WEB_LOG_LEVEL=warning
      - DEBUG=false
      - VIRTUAL_HOST=deluge.${DOMAIN}
      - VIRTUAL_PORT=8112
      - LETSENCRYPT_HOST=deluge.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/deluge:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DATA_PATH}:/mediabox
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      - mediabox-torrent
      - mediabox-proxy

  mediabox-flexget:
    image: cpoppema/docker-flexget
    container_name: mediabox-flexget
    depends_on:
      - mediabox-jackett
      - mediabox-deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - FLEXGET_LOG_LEVEL=info
      - TORRENT_PLUGIN=deluge
      - WEB_PASSWD=${FLEXGET_PASSWORD}
      - VIRTUAL_HOST=flexget.${DOMAIN}
      - VIRTUAL_PORT=5050
      - LETSENCRYPT_HOST=flexget.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/flexget:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
      - ${DATA_PATH}:/mediabox
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
    labels:
      - "io.portainer.commands.flexget-execute=/usr/bin/flexget execute"
      - "io.portainer.commands.flexget-reload=/usr/bin/flexget daemon reload-config"
      - "io.portainer.commands.flexget-check=/usr/bin/flexget check"
      - "io.portainer.commands.flexget-failed-list=/usr/bin/flexget failed list"
      - "io.portainer.commands.flexget-failed-clear=/usr/bin/flexget failed clear"
      - "io.portainer.commands.flexget-rejected-list=/usr/bin/flexget rejected list"
      - "io.portainer.commands.flexget-rejected-clear=/usr/bin/flexget rejected clear"
  
  mediabox-sonarr:
    image: linuxserver/sonarr
    container_name: mediabox-sonarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=sonarr.${DOMAIN}
      - VIRTUAL_PORT=8989
      - LETSENCRYPT_HOST=sonarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DATA_PATH}/tv:/tv
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
  
  mediabox-radarr:
    image: linuxserver/radarr
    container_name: mediabox-radarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=radarr.${DOMAIN}
      - VIRTUAL_PORT=7878
      - LETSENCRYPT_HOST=radarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DATA_PATH}/movies:/movies
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
  
  mediabox-lidarr:
    image: linuxserver/lidarr
    container_name: mediabox-lidarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=lidarr.${DOMAIN}
      - VIRTUAL_PORT=8686
      - LETSENCRYPT_HOST=lidarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/lidarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DATA_PATH}/music:/music
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy

  mediabox-bazarr:
    image: linuxserver/bazarr
    container_name: mediabox-bazarr
    depends_on:
      - mediabox-sonarr
      - mediabox-radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=bazarr.${DOMAIN}
      - VIRTUAL_PORT=6767
      - LETSENCRYPT_HOST=bazarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${DATA_PATH}/movies:/movies
      - ${DATA_PATH}/tv:/tv
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy

  mediabox-jackett:
    image: linuxserver/jackett
    container_name: mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=jackett.${DOMAIN}
      - VIRTUAL_PORT=9117
      - LETSENCRYPT_HOST=jackett.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/jackett:/config
    restart: unless-stopped
    networks:
      - mediabox-torrent
      - mediabox-proxy
  
  mediabox-jellyfin:
    image: linuxserver/jellyfin
    container_name: mediabox-jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=stream.${DOMAIN}
      - VIRTUAL_PORT=8096
      - LETSENCRYPT_HOST=stream.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${DATA_PATH}/movies:/data/movies
      - ${DATA_PATH}/tv:/data/tv
      - ${DATA_PATH}/music:/data/music
      - ${DATA_PATH}/books:/data/books
      - ${MOUNT_PATH}:/mnt/rclone:rw,rslave
    restart: unless-stopped
    networks:
      - mediabox-proxy

  mediabox-webdav:
    image: bytemark/webdav
    container_name: mediabox-webdav
    environment:
      - USERNAME=${WEBDAV_USERNAME}
      - PASSWORD=${WEBDAV_PASSWORD}
      - VIRTUAL_HOST=webdav.${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=webdav.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${DATA_PATH}:/var/lib/dav/data/mediabox
      - ${DOWNLOADS_PATH}:/var/lib/dav/data/downloads
      - ${MOUNT_PATH}:/var/lib/dav/data/mnt/rclone:rw,rslave
    restart: unless-stopped
    networks:
      - mediabox-proxy


networks:
  mediabox-torrent:
    driver: bridge
  mediabox-proxy:
    driver: bridge
