version: '3.2'

services:
  mediabox-deluge:
    image: binhex/arch-delugevpn
    container_name: mediabox-deluge
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PHP_TZ=${TIME_ZONE}
      - UMASK=022
      - NAME_SERVERS=${DELUGE_DNS}
      - LAN_NETWORK=192.168.1.0/24
      - ENABLE_PRIVOXY=no
      - STRICT_PORT_FORWARD=${DELUGE_VPN_STRICT_PORT_FORWARD}
      - VPN_PROV=${DELUGE_VPN_PROV}
      - VPN_USER=${DELUGE_VPN_USER}
      - VPN_PASS=${DELUGE_VPN_PASS}
      - VPN_ENABLED=${DELUGE_VPN_ENABLED}
      - DELUGE_DAEMON_LOG_LEVEL=warning
      - DELUGE_WEB_LOG_LEVEL=warning
      - DEBUG=false
      - VIRTUAL_HOST=${DELUGE_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=8112
      - LETSENCRYPT_HOST=${DELUGE_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/deluge:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${MOUNT_PATH}:/mnt:rw,rslave
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      - torrent
      - proxy
  
  mediabox-sonarr:
    image: linuxserver/sonarr
    container_name: mediabox-sonarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${SONARR_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=8989
      - LETSENCRYPT_HOST=${SONARR_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${MOUNT_PATH}:/mnt:rw,rslave
    restart: unless-stopped
    networks:
      - torrent
      - proxy
  
  mediabox-radarr:
    image: linuxserver/radarr
    container_name: mediabox-radarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${RADARR_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=7878
      - LETSENCRYPT_HOST=${RADARR_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${MOUNT_PATH}:/mnt:rw,rslave
    restart: unless-stopped
    networks:
      - torrent
      - proxy
  
  mediabox-lidarr:
    image: linuxserver/lidarr
    container_name: mediabox-lidarr
    depends_on:
      - mediabox-deluge
      - mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${LIDARR_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=8686
      - LETSENCRYPT_HOST=${LIDARR_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/lidarr:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${MOUNT_PATH}:/mnt:rw,rslave
    restart: unless-stopped
    networks:
      - torrent
      - proxy

  mediabox-bazarr:
    image: linuxserver/bazarr
    container_name: mediabox-bazarr
    depends_on:
      - mediabox-sonarr
      - mediabox-radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${BAZARR_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=6767
      - LETSENCRYPT_HOST=${BAZARR_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${MOUNT_PATH}:/mnt:rw,rslave
    restart: unless-stopped
    networks:
      - torrent
      - proxy

  mediabox-jackett:
    image: linuxserver/jackett
    container_name: mediabox-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${JACKETT_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=9117
      - LETSENCRYPT_HOST=${JACKETT_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/jackett:/config
    restart: unless-stopped
    networks:
      - torrent
      - proxy

  mediabox-webdav:
    image: bytemark/webdav
    container_name: mediabox-webdav
    environment:
      - USERNAME=${WEBDAV_USERNAME}
      - PASSWORD=${WEBDAV_PASSWORD}
      - VIRTUAL_HOST=${WEBDAV_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${WEBDAV_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${DOWNLOADS_PATH}:/var/lib/dav/data/downloads
      - ${MOUNT_PATH}:/var/lib/dav/data/mnt:rw,rslave
    restart: unless-stopped
    networks:
      - proxy

  mediabox-filestash:
    image: machines/filestash
    container_name: mediabox-filestash
    environment:
      - APPLICATION_URL=filestash.${DOMAIN}
      - VIRTUAL_HOST=${FILESTASH_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=8334
      - LETSENCRYPT_HOST=${FILESTASH_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: unless-stopped
    networks:
      - proxy

  mediabox-pyload:
    image: linuxserver/pyload
    container_name: mediabox-pyload
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${PYLOAD_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=${PYLOAD_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/pyload:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${MOUNT_PATH}:/mnt:rw,rslave
    restart: unless-stopped
    networks:
      - proxy

  mediabox-jellyfin:
    image: linuxserver/jellyfin
    container_name: mediabox-jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${JELLYFIN_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=8096
      - LETSENCRYPT_HOST=${JELLYFIN_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${MOUNT_PATH}:/mnt:rw,rslave
    restart: unless-stopped
    networks:
      - proxy

  mediabox-embystat:
    image: linuxserver/embystat
    container_name: mediabox-embystat
    depends_on:
      - mediabox-jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${EMBYSTAT_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=6555
      - LETSENCRYPT_HOST=${EMBYSTAT_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/embystat:/config
    restart: unless-stopped
    networks:
      - proxy

  mediabox-ombi:
    image: linuxserver/ombi
    container_name: mediabox-ombi
    depends_on:
      - mediabox-jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${OMBI_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=3579
      - LETSENCRYPT_HOST=${OMBI_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${CONFIG_PATH}/ombi:/config
    restart: unless-stopped
    networks:
      - proxy

networks:
  torrent:
    driver: bridge
  proxy:
    driver: bridge
