version: '3'

services:
  nextcloud-db:
    image: mariadb
    container_name: mediabox-nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PSW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: mediabox-nextcloud
    depends_on:
     - nextcloud-db
    ports:
      - 8282:80
    links:
      - nextcloud-db
    volumes:
      - ${DATA_PATH}:/var/www/html/data
    environment:
      - VIRTUAL_HOST=cloud.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_HOST=cloud.${DOMAIN}
      - VIRTUAL_PORT=80
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
    restart: unless-stopped
