tasks:
  # Add downloaded movies to Trakt collection.
  # You need to authorize your trakt account. See `flexget trakt auth -h` on how to.
  # Requisites:
  #   - Trakt account
  trakt-collection-movies:
    filesystem:
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
      path:
        - '{? paths.movies ?}'
    trakt_lookup: yes
    accept_all: yes
    crossmatch:
      from:
        - trakt_list:
            account: '{? trakt.account ?}'
            list: collection
      fields:
        - trakt_id
      action: reject
    list_add:
      - movie_list: movies
      - trakt_list:
          account: '{? trakt.account ?}'
          list: collection
          type: movies

  # Add downloaded tv episodes to Trakt collection.
  # You need to authorize your trakt account. See `flexget trakt auth -h` on how to.
  # Requisites:
  #   - Trakt account
  trakt-collection-tv:
    filesystem:
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
      path:
        - '{? paths.tv ?}'
    trakt_lookup: yes
    accept_all: yes
    list_add:
      - entry_list: tv
      - trakt_list:
          account: '{? trakt.account ?}'
          list: collection
          type: episodes